### ISSUE TITLE
error on mse predictor

### ISSUE THREAD

**Issue by Youwei-He** [zhandawei/Single_objective_EGO_algorithms#3]
the mse predictor of the dace toolbox is porblematic if regpoly1 or higher order regression function is used.
the line for mse in the code is "mse = dmodel.sigma2 .* (1 + u.^2 - sum(rt.^2,1))';"
While, according to the original code of DACE, it might be: "mse = dmodel.sigma2 .* (1 + sum(u.^2,1) - sum(rt.^2,1))';"

**Comment by zhandawei** [comment]
Thank you for the suggestions, I have correct the error.
